In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
array = np.array([
[1, 1],
[2, 4],
[3, 9],
[4, 6],
[4, 3],
]).astype(float)
array
# column_values = ['x', 'y']
# df = pd.DataFrame(data = array, columns = column_values)
# df

array([[1., 1.],
       [2., 4.],
       [3., 9.],
       [4., 6.],
       [4., 3.]])

In [3]:
distances = np.array([[0]*len(array)]*len(array)).astype(float)
distances

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
clusters = []
for i in range(len(distances)):
    clusters.append([i])
clusters

[[0], [1], [2], [3], [4]]

In [5]:
def euclidean(a, b):
    d = round(((a[0]-b[0])**2 + (a[1]-b[1])**2)**0.5, 1)
    return d

In [6]:
for i in range(len(distances)):
    for j in range(len(distances[i])):
        distances[i][j] = euclidean(array[i], array[j])
print(distances)

[[0.  3.2 8.2 5.8 3.6]
 [3.2 0.  5.1 2.8 2.2]
 [8.2 5.1 0.  3.2 6.1]
 [5.8 2.8 3.2 0.  3. ]
 [3.6 2.2 6.1 3.  0. ]]


In [7]:
def find_min_in_matrix(distances):
    mini = 0
    minj = 0
    minval = 1000
    for i in range(len(distances)):
        for j in range(len(distances[i])):
            if i>j:
                if minval > distances[i][j]:
                    minval = distances[i][j];
                    mini = i
                    minj = j
    return [minval, mini, minj]

In [8]:
minval, mini, minj = find_min_in_matrix(distances)
print(minval, ' ', mini, ' ', minj)

2.2   4   1


In [9]:
newcol = np.array([0]*len(distances))
distances = np.hstack((distances, np.atleast_2d(newcol).T))
newrow = np.array([0]*len(distances[0]))
distances = np.vstack((distances, np.atleast_2d(newrow)))
distances

array([[0. , 3.2, 8.2, 5.8, 3.6, 0. ],
       [3.2, 0. , 5.1, 2.8, 2.2, 0. ],
       [8.2, 5.1, 0. , 3.2, 6.1, 0. ],
       [5.8, 2.8, 3.2, 0. , 3. , 0. ],
       [3.6, 2.2, 6.1, 3. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ]])

In [10]:
def fill_matrix(distances, mini, minj):
    for i in range(len(distances)):
        if (i != mini and i != minj):
            distances[len(distances)-1][i] = min(distances[mini][i], distances[minj][i])


In [11]:
fill_matrix(distances, mini, minj)
distances

array([[0. , 3.2, 8.2, 5.8, 3.6, 3.2],
       [3.2, 0. , 5.1, 2.8, 2.2, 0. ],
       [8.2, 5.1, 0. , 3.2, 6.1, 5.1],
       [5.8, 2.8, 3.2, 0. , 3. , 2.8],
       [3.6, 2.2, 6.1, 3. , 0. , 0. ],
       [3.2, 0. , 5.1, 2.8, 0. , 0. ]])

In [12]:
first = min(mini, minj)
second = max(mini, minj)
distances = np.delete(distances, first, 1)
distances = np.delete(distances, first, 0)
distances = np.delete(distances, second-1, 1)
distances = np.delete(distances, second-1, 0)
distances

array([[0. , 8.2, 5.8, 3.2],
       [8.2, 0. , 3.2, 5.1],
       [5.8, 3.2, 0. , 2.8],
       [3.2, 5.1, 2.8, 0. ]])

In [13]:
minval, mini, minj = find_min_in_matrix(distances)
print(minval, ' ', mini, ' ', minj)

2.8   3   2


In [14]:
newcol = np.array([0]*len(distances))
distances = np.hstack((distances, np.atleast_2d(newcol).T))
newrow = np.array([0]*len(distances[0]))
distances = np.vstack((distances, np.atleast_2d(newrow)))
distances

array([[0. , 8.2, 5.8, 3.2, 0. ],
       [8.2, 0. , 3.2, 5.1, 0. ],
       [5.8, 3.2, 0. , 2.8, 0. ],
       [3.2, 5.1, 2.8, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ]])

In [15]:
fill_matrix(distances, mini, minj)
distances

array([[0. , 8.2, 5.8, 3.2, 3.2],
       [8.2, 0. , 3.2, 5.1, 3.2],
       [5.8, 3.2, 0. , 2.8, 0. ],
       [3.2, 5.1, 2.8, 0. , 0. ],
       [3.2, 3.2, 0. , 0. , 0. ]])

In [16]:
first = min(mini, minj)
second = max(mini, minj)
distances = np.delete(distances, first, 1)
distances = np.delete(distances, first, 0)
distances = np.delete(distances, second-1, 1)
distances = np.delete(distances, second-1, 0)
distances

array([[0. , 8.2, 3.2],
       [8.2, 0. , 3.2],
       [3.2, 3.2, 0. ]])

In [17]:
minval, mini, minj = find_min_in_matrix(distances)
print(minval, ' ', mini, ' ', minj)

3.2   2   0


In [18]:
newcol = np.array([0]*len(distances))
distances = np.hstack((distances, np.atleast_2d(newcol).T))
newrow = np.array([0]*len(distances[0]))
distances = np.vstack((distances, np.atleast_2d(newrow)))
distances

array([[0. , 8.2, 3.2, 0. ],
       [8.2, 0. , 3.2, 0. ],
       [3.2, 3.2, 0. , 0. ],
       [0. , 0. , 0. , 0. ]])

In [19]:
fill_matrix(distances, mini, minj)
distances

array([[0. , 8.2, 3.2, 0. ],
       [8.2, 0. , 3.2, 3.2],
       [3.2, 3.2, 0. , 0. ],
       [0. , 3.2, 0. , 0. ]])

In [20]:
first = min(mini, minj)
second = max(mini, minj)
distances = np.delete(distances, first, 1)
distances = np.delete(distances, first, 0)
distances = np.delete(distances, second-1, 1)
distances = np.delete(distances, second-1, 0)
distances

array([[0. , 3.2],
       [3.2, 0. ]])