In [1]:
#numpy exmple 1
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
#numpy exmple 2
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
#numpy example 3
#1-D Arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
#numpy example 4
#2-D Arrays
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
#numpy Example 5
#usage of .format()
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)
print("x:\n{}".format(x))

[[1 2 3]
 [4 5 6]]
x:
[[1 2 3]
 [4 5 6]]


In [6]:
#numpy Example 6
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#numpy Example 7
#Check Number of Dimensions
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many di
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
