In [2]:
#parse Example 1
#CSR - Compressed Sparse Row. For fast row slicing, faster matrix vector products
import numpy as np
from scipy.sparse import csr_matrix
arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])
print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [4]:
#parse Example 2
#create a 2d numpy array with diagonal of ones and zro everywhere
from scipy import sparse
eye=np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#parse Example 3
#convert the numpy array to a scipy sparse matrix in CSR format
#only non zero entries are stored
sparse_matrix = sparse.csr_matrix(eye)
print(sparse_matrix)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
